tumblr_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  get '/about', to: 'pages#about'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tumblr_app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

tumblr_app/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true
end

tumblr_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

tumblr_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    if @comment.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to @post
  end
end

private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

  def find_comment
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

tumblr_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

tumblr_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end
end

private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end

tumblr_app/app/helpers/comments_helper.rb
module CommentsHelper
end

tumblr_app/app/helpers/pages_helper.rb
module PagesHelper
end

tumblr_app/app/helpers/posts_helper.rb
module PostsHelper
end

tumblr_app/app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.commenter %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>

  <% if user_signed_in? %>
    <p>
      <%= link_to 'Delete', [comment.post, comment],
                   method: :delete, class: 'button',
                   data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</div>

tumblr_app/app/views/comments/_form.html.erb
<%= form_for [@post, @post.comments.build] do |f| %>
  <p>
    <%= f.label :commenter %>
    <br>
    <%= f.text_field :commenter %>
  </p>

  <p>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

tumblr_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TumblrApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway&display=swap' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div id="sidebar">
      <ul>
        <li class="category"><%=link_to 'Tumblr', root_path %></li>
        <li><%= link_to 'Posts', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>

      <% unless user_signed_in? %>
        <p class="sign_in"><%= link_to 'User Login', new_user_session_path%></p>
        <% end %>
    </div>

    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
          <p>My Page</p>
        <% else %>
          <%= link_to 'Back to Post Feed', root_path %>
        <% end %>

        <% if user_signed_in? %>
          <div class="buttons">
            <button class="button"><%= link_to 'Make Post', new_post_path %></button>
            <button class="button"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></button>
          </div>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class:'alert') %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

tumblr_app/app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag 'profile.jpg' %>
  </div>

  <div id="content">
    <h1>Mr. Stick Figure</h1>
    <p>
      Lorem ipsum dolor sit amet, exerci numquam delectus et mel, et sit dicta volumus abhorreant. Quo reque iisque
      convenire ut, sea legere aperiam discere in, ius ex aliquid laoreet similique. Adolescens signiferumque vim te.
      Mazim appetere quo id. Mea ex reque mazim dicunt, vocibus deseruisse has ex. At cum prima volutpat intellegat.

      Cu mea sint mandamus, vis ut laudem tamquam legendos. Has ad molestie omittantur signiferumque, mediocrem
      repudiandae et sit. Quaestio expetendis his an, alia putent mel ei. In essent commodo nam, suas diam meliore
      mel cu. At facer primis est, sit duis salutandi disputando cu.

      Te epicurei signiferumque his, solum detraxit iudicabit ut has. Appareat postulant ad usu. Mollis quaerendum
      vix an, ea eum homero contentiones, dico vulputate omittantur eos no. Eum in eirmod sententiae eloquentiam,
      justo posse menandri no quo. Et cum corpora mnesarchum philosophia, pri case aperiam accusata ne. An reque
      laboramus vix, brute recusabo mei in.
    </p>
  </div>
</div>

tumblr_app/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <%if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, 'error') %> stopped this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

tumblr_app/app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>

  <%= render 'form' %>
</div>

tumblr_app/app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title">
      <%= link_to post.title, post %>
    </h2>
    <p class="body">
      <%= truncate(post.body, length:100) %>
    </p>
    <p class="date">
      <%= time_ago_in_words(post.created_at) %> ago
    </p>
  </div>
<% end %>

tumblr_app/app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>

  <%= form_for @post do |f| %>

    <%if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, 'error') %> stopped this post from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %>
      <br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

tumblr_app/app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago
    <% if user_signed_in? %>
     | <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Delete', post_path(@post),
                            method: :delete,
                            data: { confirm: 'Are your sure?'} %>
      <% end %>
  </p>

  <p class="body">
    <%= @post.body%>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Join Discussion</h3>
    <%= render 'comments/form' %>
  </div>
</div>