file_cabinet_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :documents

  authenticated :user do
    root 'documents#index'
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

file_cabinet_app/app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
end

file_cabinet_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :documents
end

file_cabinet_app/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @documents = current_user.documents.order('documents.updated_at DESC')
  end

  def show
  end

  def new
    @document = current_user.documents.build
  end

  def create
    @document = current_user.documents.build(doc_params)

    if @document.save
      redirect_to @document
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @document.update(doc_params)
      redirect_to @document
    else
      render 'edit'
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_path
  end
end

private
  def doc_params
    params.require(:document).permit(:title, :body)
  end

  def find_doc
    @document = Document.find(params[:id])
  end

file_cabinet_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

file_cabinet_app/app/helpers/documents_helper.rb
module DocumentsHelper
end

file_cabinet_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

file_cabinet_app/app/views/documents/_form.html.erb
<div class="row pl-4">
  <div class="col-7">
    <%= form_for @document do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: '15' %>
      </div>

      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancel', documents_path, class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

file_cabinet_app/app/views/documents/edit.html.erb
<h1>Edit Document</h1>

<%= render 'form' %>

file_cabinet_app/app/views/documents/index.html.erb
<% if @documents.blank? %>
  <div class="jumbotron text-center mb-0">
    <h1 class="display-4">Nothing's Here!</h1>
    <p class="lead">Get started organizing your life.</p>
    <br>
    <%= link_to 'Create a New Document', new_document_path, class: 'btn btn-primary btn-lg'%>
  </div>
<% else %>
  <table class="table table-hover border-bottom" id="docs_table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Owner</th>
        <th scope="col">Last modified</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @documents.each do |doc| %>
        <tr>
          <td><%= doc.title %></td>
          <td><%= current_user.email %></td>
          <td><%= time_ago_in_words(doc.updated_at) %> ago</td>
          <td>
            <div class="btn-group">
                <%= link_to 'View', document_path(doc), class: 'btn btn-primary btn-md' %>
                <%= link_to 'Edit', edit_document_path(doc), class: 'btn btn-primary btn-md' %>
                <%= link_to 'Delete', doc,
                            method: :delete,
                            class: 'btn btn-primary btn-md',
                            data: { confirm: 'Are you sure?' }%>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

file_cabinet_app/app/views/documents/new.html.erb
<h1>New Document!</h1>

<%= render 'form' %>

file_cabinet_app/app/views/documents/show.html.erb
<div class="row">
  <div class="col-6">
    <h1><%= @document.title %></h1>

    <div class="pl-4">
      <%= simple_format(@document.body) %>
    </div>

    <br>
    <div class="buttons">
      <%= link_to 'Edit', edit_document_path(@document), class: 'btn btn-primary' %>
      <%= link_to 'Delete', document_path(@document),
                                method: :delete,
                                data: { confirm: 'Are you sure?' },
                                class: 'btn btn-primary' %>
      <%= link_to 'Back to Overview', documents_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

file_cabinet_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileCabinet | Your Life's Work</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid mb-4">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <%= link_to 'File Cabinet', root_path, class: 'navbar-brand' %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav float-right text-right pr-3 ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Create Doc', new_document_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>

<!--      <p class="notice">-->
        <%#= notice %>
<!--      </p>-->
<!--      <p class="alert">-->
        <%#= alert %>
<!--      </p>-->

      <%= yield %>
    </div>
  </body>
</html>

file_cabinet_app/app/views/welcome/index.html.erb
<div class="jumbotron text-center mb-0">
    <h1 class="display-4">Welcome to File Cabinet!</h1>
    <p class="lead">A better way to create and organize your documents<br>Your Life Organized.</p>
    <br>
    <%= link_to 'Sign Up Today!', new_user_registration_path, class: 'btn btn-primary btn-lg'%>
</div>

<div class="container-fluid">
  <div class="callout row justify-content-center align-items-center p-5">
    <div class="col-8 text-center">
      <h3 class="display-4 font-italic">About Us</h3>
      <br>
      <p class="lead">
        Lorem ipsum dolor sit amet, sed utamur quaerendum dissentiet an, sea no quem placerat facilisi.
        Ex adhuc corpora sea, ea solet everti sanctus eum. Congue omnesque epicurei ei his, melius suavitate duo no.
        Mundi vocent ius ut. Putent quodsi sed ut.
        <br><br>
        Summo percipit sapientem mel at, pro graeci senserit no, ius et sanctus lobortis temporibus.
        Aeque option singulis ne duo. In nec facer urbanitas inciderint. Mel aeque suscipit no, at usu primis
        abhorreant philosophia. Sed an oratio inciderint, pri ipsum choro dolorem ne. Has autem appellantur an.
      </p>
    </div>
  </div>

  <div class="row justify-content-center align-items-center">
    <div class="col-12 text-center">
      <p class="lead pt-5">
        Create an account to get started organizing your life today!
      </p>
        <%= link_to 'Create Account', new_user_registration_path, class: 'btn btn-primary btn-md'%>
    </div>
  </div>
</div>