instagram_app/config/routes.rb
Rails.application.routes.draw do
  resources :pics

  root 'pics#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

instagram_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

instagram_app/app/models/pic.rb
class Pic < ApplicationRecord
end

instagram_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

instagram_app/app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [:show, :edit, :update, :destroy]

  def index
    @pics = Pic.all.order('created_at DESC')
  end

  def show
  end

  def new
    @pic = Pic.new
  end

  def create
    @pic = Pic.new(pic_params)

    if @pic.save
      redirect_to @pic, notice: 'Yes! It was posted!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: 'Congrats! Pic was updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end
end

private
  def pic_params
    params.require(:pic).permit(:title, :description)
  end

  def find_pic
    @pic = Pic.find(params[:id])
  end

instagram_app/app/helpers/application_helper.rb
module ApplicationHelper
end

instagram_app/app/helpers/pics_helper.rb
module PicsHelper
end

instagram_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>

    <%= yield %>
  </body>
</html>

instagram_app/app/views/pics/_form.html.erb
<%= form_for @pic, html: {multipart: true} do |f| %>
  <% if @pic.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(@pic.errors.count, 'error') + 'prevented this pic from saving' %></h2>
      <ul>
        <% @pic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

instagram_app/app/views/pics/edit.html.erb
<h1>Edit Pic</h1>

<%= render 'form' %>

<%= link_to 'Cancel', pic_path(@pic), class: 'btn btn-primarys' %>

instagram_app/app/views/pics/index.html.erb
<% @pics.each do |pic| %>
  <h2><%= link_to pic.title, pic_path(pic) %></h2>
<% end %>

<%= link_to 'Gram It', new_pic_path, class: 'btn btn-primary' %>

instagram_app/app/views/pics/new.html.erb
<h1>Post Pic!</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

instagram_app/app/views/pics/show.html.erb
<h1><%= @pic.title %></h1>
<p><%= @pic.description %></p>

<%= link_to 'Back', root_path, class: 'btn btn-primary' %>
<%= link_to 'Edit', edit_pic_path, class: 'btn btn-primary' %>
<%= link_to 'Delete', @pic,
            class: 'btn btn-primary',
            method: :delete,
            data: { confirm: 'Are you sure?'}%>